site_name: Kop
theme:
  name: material
plugins:
  - search
markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
repo_url: https://github.com/vegaoqiang/kop
exclude_docs: |
  readme_ch.md
