apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-deployment
  labels:
    app: new-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-deployment
  template:
    metadata:
      labels:
        app: new-deployment
    spec:
      containers:
        - name: main
          image: nginx:latest
