##
#Opaque	arbitrary user-defined data
#kubernetes.io/service-account-token	ServiceAccount token
#kubernetes.io/dockercfg	serialized ~/.dockercfg file
#kubernetes.io/dockerconfigjson	serialized ~/.docker/config.json file
#kubernetes.io/basic-auth	credentials for basic authentication
#kubernetes.io/ssh-auth	credentials for SSH authentication
#kubernetes.io/tls	data for a TLS client or server
#bootstrap.kubernetes.io/token	bootstrap token data
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-name
  namespace: default
type: bootstrap.kubernetes.io/token
data:
  auth-extra-groups: c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=
  expiration: MjAyMC0wOS0xM1QwNDozOToxMFo=
  token-id: NWVtaXRq
  token-secret: a3E0Z2lodnN6emduMXAwcg==
  usage-bootstrap-authentication: dHJ1ZQ==
  usage-bootstrap-signing: dHJ1ZQ==